### ISSUE TITLE
点击浏览器刷新，页面出现抖动

### ISSUE THREAD

**Issue by bsl5115** [twelvet-s/twelvet-ui#2]
点击浏览器刷新，页面出现抖动
![1684821545911](https://github.com/twelvet-s/twelvet-ui/assets/103096046/7c2e2bff-9126-4dd1-b389-3db1334610fa)

**Comment by twelvet-s** [comment]
我看了官方的框架也是会这样的，不知道是不是官方的特性还是bug，这个需要跟antd联系查证
[官方例子](https://pro.ant.design/zh-CN/docs/getting-started/#%E5%88%9D%E5%A7%8B%E5%8C%96)
